name: Build and optionally deploy documentation
on:
  push:
jobs:
  # Note: we explicitly *build* the documentation in a job with minimal permissions.
  build:
    name: Build static site
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync --locked --all-extras --dev
      - name: Build documentation
        run: uv run zensical build
      - uses: actions/upload-pages-artifact@v5
        with:
          path: site
  deploy:
    name: Deploy to GitHub pages
    # Only try to deploy to pages if we're running on the main branch. We use ref/heads because,
    # technically, one could create a "tag" named main too.
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from GitHub itself
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
